services:

  backend:
    build:
      context: ./backend/cache-manager-backend
    container_name: cache-manager-backend
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/cache_demo
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build:
      context: ./frontend/cache-manager-frontend
    container_name: cache-manager-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend